name: "Tests"
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, labeled, unlabeled ]
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 
      - run: | 
          echo "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          git fetch 
          git checkout zeme-test
          echo MERGEBASE "$(git merge-base HEAD origin/main)"
          echo REVPARSE "$(git rev-parse --short HEAD)"
                


# git checkout main ; git add . ; git commit -m wip ; git push ; git checkout zeme-test ; git pull --rebase origin main ; git push -f